name: processlai
dependencies:
    - python 2.7*
    - keyring >=9.3.1
    - keyrings.alt >=1.2
#    - gdal 2.1*
    - gdal
    - pymodis
    - pycurl
    #- pandas ==0.18.1
    - pandas
    - simplejson
    - geocoder
    - python-wget
    - hdf4
    - pyproj
    - szip
#    - projectmasgetlandsat